version: '3.8'

services:
  # web_server:
  #   build:
  #     context: ../../web_server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ../../web_server:/app
  #   depends_on:
  #     - api_server

  api_server:
    build:
      context: ../../api_server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../api_server:/app